---
- hosts: localhost
  tasks:

  - name: set variables
    set_fact:
      vm_ipv4_address: 192.168.23.100
      vm_network: 192.168.23.0/24
      vm_ext_port: 3389
      vm_int_port: 3389
      vmbr_name: vmbr23
      vmbr_ipv4_address: 192.168.23.1
      vmbr_ipv4_netmask: 255.255.255.0


  - name: copy hosts template
    template:
      src: hosts.j2
      dest: /etc/hosts
      backup: yes

  - name: copy interfaces template
    template:
      src: interfaces.j2
      dest: /etc/network/interfaces
      backup: yes

  - name: create iptables folder
    file:
      dest: /etc/iptables
      state: directory


  - name: copy rules template
    template:
      src: rules.j2
      dest: /etc/iptables/rules
      backup: yes

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: install basic packages
    apt:
      pkg:
      - aptitude
      - gpg-agent
      - mc
      - htop
      - iotop
      - sysstat
      - nload
      - lshw
      - iptables-persistent
      - screen
      - mlocate
      - certbot
      - isc-dhcp-server
      - dirmngr 
      - gnupg-l10n 
      - psmisc
      - pigz
      - tcpdump
      - sudo

  - name: disable ipv6 in sysctl
    shell: echo "# IPv6 disabled \n net.ipv6.conf.all.disable_ipv6 = 1 \n net.ipv6.conf.default.disable_ipv6 = 1 \n net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf

  - name: adjust rebuild raid speed in sysctl
    shell: echo "# adjust rebuild raid speed \n dev.raid.speed_limit_min = 100000 \n dev.raid.speed_limit_max = 2000000" >> /etc/sysctl.conf

  - name: Add prox apt signing key
    ansible.builtin.apt_key:
      url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
      state: present
      
  - name: add prox repo
    apt_repository:
      repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release|lower }} pve-no-subscription"
      state: present
      filename: 'pve-install-repo.list'

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: install prox packages
    apt:
      pkg:
      - proxmox-ve
      - postfix
      - open-iscsi
      - ksm-control-daemon

  - name: remove os-prober
    action: >
      {{ ansible_pkg_mgr }} name=os-prober state=absent

  - name: remove pve-subscription file
    file:
      dest: /etc/apt/sources.list.d/pve-enterprise.list
      state: absent
      
  - name: copy dhcp default
    template:
      src: isc-dhcp-server.j2
      dest: /etc/default/isc-dhcp-server
      backup: yes

  - name: copy dhcp rules
    template:
      src: dhcpd.conf.j2
      dest: /etc/dhcp/dhcpd.conf
      backup: yes

  - name: Set timezone to Europe/Kiev
    community.general.timezone:
      name: Europe/Kiev


  - debug:
      msg: "run command pvecm updatecerts -f for temporary bugfix https://forum.proxmox.com/threads/problem-after-proxmox-installation-no-www-interface.42909/"

